# Generated by Django 4.1.6 on 2023-02-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-4-12'),
            preserve_default=False,
        ),
    ]
